import { useState } from "react";
import { useNavigate } from "react-router-dom";

import PageContainer from "../../components/layout/PageContainer";
import Button from "../../components/common/Button";
import Input from "../../components/common/Input";
import Select from "../../components/common/Select";

import "./CreateEvent.css";

function CreateEvent() {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    name: "",
    description: "",
    organization: "",
    startDate: "",
    endDate: "",
    location: "",
    college: "",
    year: "",
    contactEmail: "",
    contactPhone: "",
  });

  const [isSubmitting, setIsSubmitting] =
    useState(false);

  const [error, setError] = useState("");

  const [createdEvent, setCreatedEvent] =
    useState(null);

  const handleChange = (event) => {
    const { name, value } = event.target;

    setFormData((previous) => ({
      ...previous,
      [name]: value,
    }));

    setError("");
  };

  const handleSubmit = async (event) => {
    event.preventDefault();

    setError("");

    // Basic validation

    if (
      !formData.name.trim() ||
      !formData.startDate ||
      !formData.endDate
    ) {
      setError(
        "Please fill in all required fields."
      );

      return;
    }

    try {
      setIsSubmitting(true);

      /*
       * TEMPORARY API STRUCTURE
       *
       * Later replace this with your actual
       * eventService.js API call:
       *
       * const response =
       *   await createEvent(formData);
       */

      const response = await fetch(
        "/api/events",
        {
          method: "POST",

          headers: {
            "Content-Type":
              "application/json",

            // Authentication token will be added
            // here when auth is integrated.
            //
            // Authorization:
            // `Bearer ${token}`,
          },

          body: JSON.stringify(formData),
        }
      );

      if (!response.ok) {
        throw new Error(
          "Failed to create event."
        );
      }

      const data = await response.json();

      /*
       * Expected backend response could be
       * something like:
       *
       * {
       *   eventId: "...",
       *   trackingSlug: "...",
       *   trackingUrl: "..."
       * }
       */

      setCreatedEvent(data);

    } catch (err) {
      console.error(err);

      setError(
        "Unable to create the event. Please try again."
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReset = () => {
    setFormData({
      name: "",
      description: "",
      organization: "",
      startDate: "",
      endDate: "",
      location: "",
      college: "",
      year: "",
      contactEmail: "",
      contactPhone: "",
    });

    setCreatedEvent(null);
    setError("");
  };

  const copyTrackingLink = () => {
    if (
      createdEvent?.trackingUrl
    ) {
      navigator.clipboard.writeText(
        createdEvent.trackingUrl
      );
    }
  };

  /*
   * Success screen
   */

  if (createdEvent) {
    return (
      <PageContainer
        title="Event Created"
        subtitle="Your event has been successfully created."
      >
        <div className="create-event-success">

          <div className="success-icon">
            ✓
          </div>

          <h2>
            Event created successfully!
          </h2>

          <p>
            Your event is now ready to accept
            student registrations.
          </p>

          <div className="tracking-link-card">

            <div className="tracking-link-header">
              <div>
                <span>
                  STUDENT TRACKING LINK
                </span>

                <h3>
                  Share this link with students
                </h3>
              </div>

              <div className="link-icon">
                ↗
              </div>
            </div>

            <div className="tracking-link-box">

              <span>
                {createdEvent.trackingUrl ||
                  createdEvent.trackingSlug ||
                  "Tracking link generated by backend"}
              </span>

              <button
                onClick={copyTrackingLink}
              >
                Copy
              </button>

            </div>

            {createdEvent.trackingSlug && (
              <p className="tracking-slug">
                Tracking slug:{" "}
                <strong>
                  {createdEvent.trackingSlug}
                </strong>
              </p>
            )}

          </div>

          <div className="success-actions">

            <Button
              variant="secondary"
              onClick={() =>
                navigate("/admin/events")
              }
            >
              View Events
            </Button>

            <Button
              onClick={handleReset}
            >
              Create Another Event
            </Button>

          </div>

        </div>
      </PageContainer>
    );
  }

  return (
    <PageContainer
      title="Create Event"
      subtitle="Create a new event and start collecting student applications."
      actions={
        <Button
          variant="secondary"
          onClick={() =>
            navigate("/admin/events")
          }
        >
          ← Back to Events
        </Button>
      }
    >
      <form
        className="create-event-form"
        onSubmit={handleSubmit}
      >

        {/* Error */}

        {error && (
          <div className="create-event-error">
            <span>!</span>
            {error}
          </div>
        )}

        {/* Basic Information */}

        <section className="create-event-section">

          <div className="create-event-section-heading">

            <div className="section-number">
              01
            </div>

            <div>
              <h3>
                Basic Information
              </h3>

              <p>
                Add the main details of your event.
              </p>
            </div>

          </div>

          <div className="create-event-grid">

            <div className="form-field full-width">

              <label>
                Event Name
                <span>*</span>
              </label>

              <Input
                name="name"
                value={formData.name}
                onChange={handleChange}
                placeholder="e.g. Student Leadership Program"
              />

            </div>

            <div className="form-field full-width">

              <label>
                Description
              </label>

              <textarea
                name="description"
                value={formData.description}
                onChange={handleChange}
                placeholder="Describe the event and what students can expect..."
                rows="4"
              />

            </div>

            <div className="form-field">

              <label>
                Organization
              </label>

              <Input
                name="organization"
                value={
                  formData.organization
                }
                onChange={handleChange}
                placeholder="Organization name"
              />

            </div>

            <div className="form-field">

              <label>
                Location
              </label>

              <Input
                name="location"
                value={formData.location}
                onChange={handleChange}
                placeholder="e.g. Pune"
              />

            </div>

          </div>

        </section>

        {/* Event Schedule */}

        <section className="create-event-section">

          <div className="create-event-section-heading">

            <div className="section-number">
              02
            </div>

            <div>
              <h3>
                Event Schedule
              </h3>

              <p>
                Set the duration of your event.
              </p>
            </div>

          </div>

          <div className="create-event-grid">

            <div className="form-field">

              <label>
                Start Date
                <span>*</span>
              </label>

              <Input
                type="datetime-local"
                name="startDate"
                value={
                  formData.startDate
                }
                onChange={handleChange}
              />

            </div>

            <div className="form-field">

              <label>
                End Date
                <span>*</span>
              </label>

              <Input
                type="datetime-local"
                name="endDate"
                value={
                  formData.endDate
                }
                onChange={handleChange}
              />

            </div>

          </div>

        </section>

        {/* Target Audience */}

        <section className="create-event-section">

          <div className="create-event-section-heading">

            <div className="section-number">
              03
            </div>

            <div>
              <h3>
                Target Audience
              </h3>

              <p>
                Define who can register for this event.
              </p>
            </div>

          </div>

          <div className="create-event-grid">

            <div className="form-field">

              <label>
                College
              </label>

              <Select
                name="college"
                value={formData.college}
                onChange={handleChange}
                options={[
                  {
                    value: "",
                    label: "All Colleges",
                  },
                  {
                    value: "VIT Pune",
                    label: "VIT Pune",
                  },
                  {
                    value: "COEP",
                    label: "COEP",
                  },
                  {
                    value: "SPIT",
                    label: "SPIT",
                  },
                  {
                    value: "PCCOE",
                    label: "PCCOE",
                  },
                ]}
              />

            </div>

            <div className="form-field">

              <label>
                Student Year
              </label>

              <Select
                name="year"
                value={formData.year}
                onChange={handleChange}
                options={[
                  {
                    value: "",
                    label: "All Years",
                  },
                  {
                    value: "First Year",
                    label: "First Year",
                  },
                  {
                    value: "Second Year",
                    label: "Second Year",
                  },
                  {
                    value: "Third Year",
                    label: "Third Year",
                  },
                  {
                    value: "Final Year",
                    label: "Final Year",
                  },
                ]}
              />

            </div>

          </div>

        </section>

        {/* Contact */}

        <section className="create-event-section">

          <div className="create-event-section-heading">

            <div className="section-number">
              04
            </div>

            <div>
              <h3>
                Contact Information
              </h3>

              <p>
                Provide contact details for students.
              </p>
            </div>

          </div>

          <div className="create-event-grid">

            <div className="form-field">

              <label>
                Contact Email
              </label>

              <Input
                type="email"
                name="contactEmail"
                value={
                  formData.contactEmail
                }
                onChange={handleChange}
                placeholder="contact@example.com"
              />

            </div>

            <div className="form-field">

              <label>
                Contact Phone
              </label>

              <Input
                type="tel"
                name="contactPhone"
                value={
                  formData.contactPhone
                }
                onChange={handleChange}
                placeholder="+91 XXXXX XXXXX"
              />

            </div>

          </div>

        </section>

        {/* Bottom Actions */}

        <div className="create-event-actions">

          <button
            type="button"
            className="create-event-cancel"
            onClick={() =>
              navigate("/admin/events")
            }
          >
            Cancel
          </button>

          <Button
            type="submit"
            disabled={isSubmitting}
          >
            {isSubmitting
              ? "Creating Event..."
              : "Create Event →"}
          </Button>

        </div>

      </form>
    </PageContainer>
  );
}

export default CreateEvent;